### ISSUE TITLE
`JuliaOptions` does not seem to be implemented in v2.0.0

### ISSUE THREAD

**Issue by BambOoxX** [HyperSphereStudio/JULIA.Net#7]
Hi and thanks again for your effort. I just started testing this library. 

While trying to reproduce you example in the github's frontpage, I could not find how to specify `JuliaOptions`. Was this renamed ?
Also it seems `Julia.Init` can only accept an optional string argument. 

https://github.com/HyperSphereStudio/JULIA.Net/blob/4d1fbe4360cae909840641bb1f7e0b5537908acb/src/csharp/Julia.cs#L49-L71

Was the example implementation valid only in 1.x.x, or should it still work ?

**Comment by HyperSphereStudio** [comment]
Oops! I will release the latest version I have.


I havent worked on this library in a while. It still has the memory management problem (GC push doesnt work). I will work on it a little bit to see if I can fix it before I release it

**Comment by HyperSphereStudio** [comment]
Alright I released the new version with it in it and some other changes!
